[project]
name = "repo-to-md"
version = "0.1.0"
description = "Convert a repo into a single markdown file."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["click>=8.2.1"]

[project.scripts]
repo-to-md = "main:cli"
